CREATE TABLE `group` (
  `id_group` INTEGER(11) NOT NULL AUTO_INCREMENT,
  `name_group` VARCHAR(20) DEFAULT NULL,
  `memo_group` VARCHAR(100) DEFAULT NULL,
  `parent_group` VARCHAR(20) DEFAULT NULL,
  `address_group` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`id_group`) COMMENT ''
) ENGINE=InnoDB
CHECKSUM=0
DELAY_KEY_WRITE=0
PACK_KEYS=0
AUTO_INCREMENT=0
AVG_ROW_LENGTH=0
MIN_ROWS=0
MAX_ROWS=0
ROW_FORMAT=DEFAULT
KEY_BLOCK_SIZE=0;